name: تشغيل البوت

on:
  workflow_dispatch:
  push:

jobs:
  تشغيل:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل الملفات
        uses: actions/checkout@v4

      - name: تشغيل بايثون
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: تشغيل البوت
        run: python bot.py
